name: menpodetect_rtd
channels:
  - conda-forge
dependencies:
  - python
  - setuptools
  - pip

  # Note that dlib and opencv are mocked otherwise readthedocs runs out of
  # memory setting up the environment
  - menpo >=0.9,<0.11
  - pip:
      - sphinx >=2,<3
      - sphinx_rtd_theme
      - sphinxmapxrefrole >=0.2
